#!/usr/bin/env bash
# AI Studio — Linux edition installer
set -euo pipefail

LINUX_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${AI_STUDIO_DIR:-$(cd "$LINUX_DIR/.." && pwd)}"
DATA_DIR="${AI_STUDIO_DATA:-/var/lib/ai-studio}"
ENV_FILE="${DATA_DIR}/config/env"
PROFILE="${AI_STUDIO_PROFILE:-}"

log() { echo "==> $*"; }
warn() { echo "!! $*" >&2; }

require_debian() {
  if [[ ! -f /etc/debian_version ]]; then
    warn "Tested on Debian 12 / Ubuntu 22.04+. Other distros may work but are unsupported."
  fi
}

source "${LINUX_DIR}/scripts/detect-gpu.sh"

write_env() {
  mkdir -p "${DATA_DIR}/config" "${DATA_DIR}/models" "${DATA_DIR}/output" "${DATA_DIR}/logs"
  mkdir -p "${DATA_DIR}/toolkit/outputs" "${DATA_DIR}/toolkit/inbox"
  cat >"$ENV_FILE" <<EOF
# Generated by AI Studio Linux install
AI_STUDIO_DATA=${DATA_DIR}
AI_STUDIO_PROFILE=${PROFILE}
AI_STUDIO_REPO_ROOT=${REPO_ROOT}
COMFY_PORT=7871
ACE_PORT=7870
HUB_PORT=7880
COMFY_URL=http://127.0.0.1:7871
ACE_URL=http://127.0.0.1:7870
EOF
}

install_base_packages() {
  log "Installing base packages..."
  apt-get update -qq
  apt-get install -y -qq \
    ca-certificates curl git jq \
    python3 python3-pip python3-venv \
    ffmpeg \
    systemd
}

main() {
  require_debian

  if [[ -z "$PROFILE" ]]; then
    detect_gpu_profile
    PROFILE="${DETECTED_PROFILE:-cpu}"
  fi

  log "AI Studio Linux install"
  log "Repo:    $REPO_ROOT"
  log "Profile: $PROFILE"
  log "Data:    $DATA_DIR"

  install_base_packages
  write_env

  case "$PROFILE" in
    docker-nvidia)
      bash "${LINUX_DIR}/scripts/install-docker.sh" nvidia
      bash "${LINUX_DIR}/scripts/up-docker.sh"
      ;;
    native-rocm)
      bash "${LINUX_DIR}/scripts/install-native.sh" rocm
      bash "${LINUX_DIR}/scripts/up-native.sh"
      ;;
    cpu)
      bash "${LINUX_DIR}/scripts/install-docker.sh" cpu
      bash "${LINUX_DIR}/scripts/up-docker.sh"
      ;;
    *)
      echo "ERROR: unknown profile: $PROFILE" >&2
      exit 1
      ;;
  esac

  bash "${LINUX_DIR}/scripts/install-hub.sh"

  local host
  host="$(hostname -I 2>/dev/null | awk '{print $1}')"
  [[ -z "$host" ]] && host="127.0.0.1"

  cat <<EOF

============================================
 AI Studio Linux — installed
============================================
 Profile:  $PROFILE
 Data:     $DATA_DIR
 Dashboard: http://${host}:7880/
 ComfyUI:   http://${host}:7871/
 ACE-Step:  http://${host}:7870/

 Commands:
   ${REPO_ROOT}/linux/scripts/status.sh
   ${REPO_ROOT}/linux/scripts/restart.sh
   ${REPO_ROOT}/linux/scripts/stop.sh

 Update:
   curl -fsSL https://raw.githubusercontent.com/lobrzut/ai-studio/main/linux/bootstrap.sh | sudo bash
============================================
EOF
}

main "$@"
